---
- name: install zsh
  hosts: all
  become: yes
  become_method: su
  tasks:
    - name: install zsh
      apt:
        name: zsh
        state: present
        update_cache: true
      become: true
